figma.codegen.on("generate", (event) => {
  return event.node.getCSSAsync().then((css) => {
    // `css` is an object containing the CSS generated by Figma
    // You can use `reduce` to turn it into a string...
    const code = Object.entries(css)
      .reduce((acc, [key, value]) => {
        // ...and perform any modifications you want
        value = modifyCss(value);

        return `${acc}${key}: ${value};\n`;
      }, "")
      .trim();

    return [
      {
        language: "CSS",
        code,
        title: "Example CSS Modifier",
      },
    ];
  });
});

function modifyCss(value: string) {
  // Replace anything after a comma in a var() with nothing
  value = value.replace(/(var\([^,]*),[^)]*\)/g, "$1)");
  return value;
}
